window.esdocSearchIndex = [
  [
    "./api/application.js~application",
    "class/api/Application.js~Application.html",
    "<span>Application</span> <span class=\"search-result-import-path\">./api/Application.js</span>",
    "class"
  ],
  [
    "./api/artboard.js~artboard",
    "class/api/Artboard.js~Artboard.html",
    "<span>Artboard</span> <span class=\"search-result-import-path\">./api/Artboard.js</span>",
    "class"
  ],
  [
    "./api/document.js~document",
    "class/api/Document.js~Document.html",
    "<span>Document</span> <span class=\"search-result-import-path\">./api/Document.js</span>",
    "class"
  ],
  [
    "./api/group.js~group",
    "class/api/Group.js~Group.html",
    "<span>Group</span> <span class=\"search-result-import-path\">./api/Group.js</span>",
    "class"
  ],
  [
    "./api/image.js~image",
    "class/api/Image.js~Image.html",
    "<span>Image</span> <span class=\"search-result-import-path\">./api/Image.js</span>",
    "class"
  ],
  [
    "./api/layer.js~layer",
    "class/api/Layer.js~Layer.html",
    "<span>Layer</span> <span class=\"search-result-import-path\">./api/Layer.js</span>",
    "class"
  ],
  [
    "./api/page.js~page",
    "class/api/Page.js~Page.html",
    "<span>Page</span> <span class=\"search-result-import-path\">./api/Page.js</span>",
    "class"
  ],
  [
    "./api/rectangle.js~rectangle",
    "class/api/Rectangle.js~Rectangle.html",
    "<span>Rectangle</span> <span class=\"search-result-import-path\">./api/Rectangle.js</span>",
    "class"
  ],
  [
    "./api/selection.js~selection",
    "class/api/Selection.js~Selection.html",
    "<span>Selection</span> <span class=\"search-result-import-path\">./api/Selection.js</span>",
    "class"
  ],
  [
    "./api/shape.js~shape",
    "class/api/Shape.js~Shape.html",
    "<span>Shape</span> <span class=\"search-result-import-path\">./api/Shape.js</span>",
    "class"
  ],
  [
    "./api/style.js~style",
    "class/api/Style.js~Style.html",
    "<span>Style</span> <span class=\"search-result-import-path\">./api/Style.js</span>",
    "class"
  ],
  [
    "./api/tester.js~tester",
    "class/api/Tester.js~Tester.html",
    "<span>Tester</span> <span class=\"search-result-import-path\">./api/Tester.js</span>",
    "class"
  ],
  [
    "./api/text.js~text",
    "class/api/Text.js~Text.html",
    "<span>Text</span> <span class=\"search-result-import-path\">./api/Text.js</span>",
    "class"
  ],
  [
    "./api/wrappedobject.js~wrappedobject",
    "class/api/WrappedObject.js~WrappedObject.html",
    "<span>WrappedObject</span> <span class=\"search-result-import-path\">./api/WrappedObject.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "api/api.js",
    "file/api/API.js.html",
    "api/API.js",
    "file"
  ],
  [
    "api/application.js",
    "file/api/Application.js.html",
    "api/Application.js",
    "file"
  ],
  [
    "api/application.js~application#application",
    "class/api/Application.js~Application.html#instance-member-Application",
    "api/Application.js~Application#Application",
    "member"
  ],
  [
    "api/application.js~application#artboard",
    "class/api/Application.js~Application.html#instance-member-Artboard",
    "api/Application.js~Application#Artboard",
    "member"
  ],
  [
    "api/application.js~application#document",
    "class/api/Application.js~Application.html#instance-member-Document",
    "api/Application.js~Application#Document",
    "member"
  ],
  [
    "api/application.js~application#group",
    "class/api/Application.js~Application.html#instance-member-Group",
    "api/Application.js~Application#Group",
    "member"
  ],
  [
    "api/application.js~application#image",
    "class/api/Application.js~Application.html#instance-member-Image",
    "api/Application.js~Application#Image",
    "member"
  ],
  [
    "api/application.js~application#page",
    "class/api/Application.js~Application.html#instance-member-Page",
    "api/Application.js~Application#Page",
    "member"
  ],
  [
    "api/application.js~application#rectangle",
    "class/api/Application.js~Application.html#instance-member-Rectangle",
    "api/Application.js~Application#Rectangle",
    "member"
  ],
  [
    "api/application.js~application#selection",
    "class/api/Application.js~Application.html#instance-member-Selection",
    "api/Application.js~Application#Selection",
    "member"
  ],
  [
    "api/application.js~application#shape",
    "class/api/Application.js~Application.html#instance-member-Shape",
    "api/Application.js~Application#Shape",
    "member"
  ],
  [
    "api/application.js~application#style",
    "class/api/Application.js~Application.html#instance-member-Style",
    "api/Application.js~Application#Style",
    "member"
  ],
  [
    "api/application.js~application#text",
    "class/api/Application.js~Application.html#instance-member-Text",
    "api/Application.js~Application#Text",
    "member"
  ],
  [
    "api/application.js~application#alert",
    "class/api/Application.js~Application.html#instance-method-alert",
    "api/Application.js~Application#alert",
    "method"
  ],
  [
    "api/application.js~application#api_version",
    "class/api/Application.js~Application.html#instance-get-api_version",
    "api/Application.js~Application#api_version",
    "member"
  ],
  [
    "api/application.js~application#assert",
    "class/api/Application.js~Application.html#instance-method-assert",
    "api/Application.js~Application#assert",
    "method"
  ],
  [
    "api/application.js~application#build",
    "class/api/Application.js~Application.html#instance-get-build",
    "api/Application.js~Application#build",
    "member"
  ],
  [
    "api/application.js~application#constructor",
    "class/api/Application.js~Application.html#instance-constructor-constructor",
    "api/Application.js~Application#constructor",
    "method"
  ],
  [
    "api/application.js~application#context",
    "class/api/Application.js~Application.html#instance-get-context",
    "api/Application.js~Application#context",
    "member"
  ],
  [
    "api/application.js~application#full_version",
    "class/api/Application.js~Application.html#instance-get-full_version",
    "api/Application.js~Application#full_version",
    "member"
  ],
  [
    "api/application.js~application#getselectionfromuser",
    "class/api/Application.js~Application.html#instance-method-getSelectionFromUser",
    "api/Application.js~Application#getSelectionFromUser",
    "method"
  ],
  [
    "api/application.js~application#getstringfromuser",
    "class/api/Application.js~Application.html#instance-method-getStringFromUser",
    "api/Application.js~Application#getStringFromUser",
    "method"
  ],
  [
    "api/application.js~application#log",
    "class/api/Application.js~Application.html#instance-method-log",
    "api/Application.js~Application#log",
    "method"
  ],
  [
    "api/application.js~application#message",
    "class/api/Application.js~Application.html#instance-method-message",
    "api/Application.js~Application#message",
    "method"
  ],
  [
    "api/application.js~application#newdocument",
    "class/api/Application.js~Application.html#instance-method-newDocument",
    "api/Application.js~Application#newDocument",
    "method"
  ],
  [
    "api/application.js~application#resourcenamed",
    "class/api/Application.js~Application.html#instance-method-resourceNamed",
    "api/Application.js~Application#resourceNamed",
    "method"
  ],
  [
    "api/application.js~application#rununittests",
    "class/api/Application.js~Application.html#instance-method-runUnitTests",
    "api/Application.js~Application#runUnitTests",
    "method"
  ],
  [
    "api/application.js~application#selecteddocument",
    "class/api/Application.js~Application.html#instance-get-selectedDocument",
    "api/Application.js~Application#selectedDocument",
    "member"
  ],
  [
    "api/application.js~application#setsettingforkey",
    "class/api/Application.js~Application.html#instance-method-setSettingForKey",
    "api/Application.js~Application#setSettingForKey",
    "method"
  ],
  [
    "api/application.js~application#settingforkey",
    "class/api/Application.js~Application.html#instance-method-settingForKey",
    "api/Application.js~Application#settingForKey",
    "method"
  ],
  [
    "api/application.js~application#version",
    "class/api/Application.js~Application.html#instance-get-version",
    "api/Application.js~Application#version",
    "member"
  ],
  [
    "api/application.js~application#wrapobject",
    "class/api/Application.js~Application.html#instance-method-wrapObject",
    "api/Application.js~Application#wrapObject",
    "method"
  ],
  [
    "api/application.js~application#wrappermappings",
    "class/api/Application.js~Application.html#instance-method-wrapperMappings",
    "api/Application.js~Application#wrapperMappings",
    "method"
  ],
  [
    "api/application.js~application.tests",
    "class/api/Application.js~Application.html#static-method-tests",
    "api/Application.js~Application.tests",
    "method"
  ],
  [
    "api/artboard.js",
    "file/api/Artboard.js.html",
    "api/Artboard.js",
    "file"
  ],
  [
    "api/artboard.js~artboard#constructor",
    "class/api/Artboard.js~Artboard.html#instance-constructor-constructor",
    "api/Artboard.js~Artboard#constructor",
    "method"
  ],
  [
    "api/artboard.js~artboard#isartboard",
    "class/api/Artboard.js~Artboard.html#instance-get-isArtboard",
    "api/Artboard.js~Artboard#isArtboard",
    "member"
  ],
  [
    "api/artboard.js~artboard.tests",
    "class/api/Artboard.js~Artboard.html#static-method-tests",
    "api/Artboard.js~Artboard.tests",
    "method"
  ],
  [
    "api/document.js",
    "file/api/Document.js.html",
    "api/Document.js",
    "file"
  ],
  [
    "api/document.js~document#centeronlayer",
    "class/api/Document.js~Document.html#instance-method-centerOnLayer",
    "api/Document.js~Document#centerOnLayer",
    "method"
  ],
  [
    "api/document.js~document#constructor",
    "class/api/Document.js~Document.html#instance-constructor-constructor",
    "api/Document.js~Document#constructor",
    "method"
  ],
  [
    "api/document.js~document#iteratewithnativelayers",
    "class/api/Document.js~Document.html#instance-method-iterateWithNativeLayers",
    "api/Document.js~Document#iterateWithNativeLayers",
    "method"
  ],
  [
    "api/document.js~document#layernamed",
    "class/api/Document.js~Document.html#instance-method-layerNamed",
    "api/Document.js~Document#layerNamed",
    "method"
  ],
  [
    "api/document.js~document#layerwithid",
    "class/api/Document.js~Document.html#instance-method-layerWithID",
    "api/Document.js~Document#layerWithID",
    "method"
  ],
  [
    "api/document.js~document#pages",
    "class/api/Document.js~Document.html#instance-get-pages",
    "api/Document.js~Document#pages",
    "member"
  ],
  [
    "api/document.js~document#selectedlayers",
    "class/api/Document.js~Document.html#instance-get-selectedLayers",
    "api/Document.js~Document#selectedLayers",
    "member"
  ],
  [
    "api/document.js~document#selectedpage",
    "class/api/Document.js~Document.html#instance-get-selectedPage",
    "api/Document.js~Document#selectedPage",
    "member"
  ],
  [
    "api/document.js~document#wrapobject",
    "class/api/Document.js~Document.html#instance-method-wrapObject",
    "api/Document.js~Document#wrapObject",
    "method"
  ],
  [
    "api/document.js~document.tests",
    "class/api/Document.js~Document.html#static-method-tests",
    "api/Document.js~Document.tests",
    "method"
  ],
  [
    "api/group.js",
    "file/api/Group.js.html",
    "api/Group.js",
    "file"
  ],
  [
    "api/group.js~group#adjusttofit",
    "class/api/Group.js~Group.html#instance-method-adjustToFit",
    "api/Group.js~Group#adjustToFit",
    "method"
  ],
  [
    "api/group.js~group#constructor",
    "class/api/Group.js~Group.html#instance-constructor-constructor",
    "api/Group.js~Group#constructor",
    "method"
  ],
  [
    "api/group.js~group#isgroup",
    "class/api/Group.js~Group.html#instance-get-isGroup",
    "api/Group.js~Group#isGroup",
    "member"
  ],
  [
    "api/group.js~group#iterate",
    "class/api/Group.js~Group.html#instance-method-iterate",
    "api/Group.js~Group#iterate",
    "method"
  ],
  [
    "api/group.js~group#iteratewithfilter",
    "class/api/Group.js~Group.html#instance-method-iterateWithFilter",
    "api/Group.js~Group#iterateWithFilter",
    "method"
  ],
  [
    "api/group.js~group#newgroup",
    "class/api/Group.js~Group.html#instance-method-newGroup",
    "api/Group.js~Group#newGroup",
    "method"
  ],
  [
    "api/group.js~group#newimage",
    "class/api/Group.js~Group.html#instance-method-newImage",
    "api/Group.js~Group#newImage",
    "method"
  ],
  [
    "api/group.js~group#newshape",
    "class/api/Group.js~Group.html#instance-method-newShape",
    "api/Group.js~Group#newShape",
    "method"
  ],
  [
    "api/group.js~group#newtext",
    "class/api/Group.js~Group.html#instance-method-newText",
    "api/Group.js~Group#newText",
    "method"
  ],
  [
    "api/group.js~group#pagerecttolocalrect",
    "class/api/Group.js~Group.html#instance-method-pageRectToLocalRect",
    "api/Group.js~Group#pageRectToLocalRect",
    "method"
  ],
  [
    "api/group.js~group.tests",
    "class/api/Group.js~Group.html#static-method-tests",
    "api/Group.js~Group.tests",
    "method"
  ],
  [
    "api/image.js",
    "file/api/Image.js.html",
    "api/Image.js",
    "file"
  ],
  [
    "api/image.js~image#constructor",
    "class/api/Image.js~Image.html#instance-constructor-constructor",
    "api/Image.js~Image#constructor",
    "method"
  ],
  [
    "api/image.js~image#imageurl",
    "class/api/Image.js~Image.html#instance-set-imageURL",
    "api/Image.js~Image#imageURL",
    "member"
  ],
  [
    "api/image.js~image#isimage",
    "class/api/Image.js~Image.html#instance-get-isImage",
    "api/Image.js~Image#isImage",
    "member"
  ],
  [
    "api/image.js~image.tests",
    "class/api/Image.js~Image.html#static-method-tests",
    "api/Image.js~Image.tests",
    "method"
  ],
  [
    "api/layer.js",
    "file/api/Layer.js.html",
    "api/Layer.js",
    "file"
  ],
  [
    "api/layer.js~layer#addtoselection",
    "class/api/Layer.js~Layer.html#instance-method-addToSelection",
    "api/Layer.js~Layer#addToSelection",
    "method"
  ],
  [
    "api/layer.js~layer#constructor",
    "class/api/Layer.js~Layer.html#instance-constructor-constructor",
    "api/Layer.js~Layer#constructor",
    "method"
  ],
  [
    "api/layer.js~layer#container",
    "class/api/Layer.js~Layer.html#instance-get-container",
    "api/Layer.js~Layer#container",
    "member"
  ],
  [
    "api/layer.js~layer#deselect",
    "class/api/Layer.js~Layer.html#instance-method-deselect",
    "api/Layer.js~Layer#deselect",
    "method"
  ],
  [
    "api/layer.js~layer#duplicate",
    "class/api/Layer.js~Layer.html#instance-method-duplicate",
    "api/Layer.js~Layer#duplicate",
    "method"
  ],
  [
    "api/layer.js~layer#export",
    "class/api/Layer.js~Layer.html#instance-method-export",
    "api/Layer.js~Layer#export",
    "method"
  ],
  [
    "api/layer.js~layer#exportoptionsmergedwithdefaults",
    "class/api/Layer.js~Layer.html#instance-method-exportOptionsMergedWithDefaults",
    "api/Layer.js~Layer#exportOptionsMergedWithDefaults",
    "method"
  ],
  [
    "api/layer.js~layer#frame",
    "class/api/Layer.js~Layer.html#instance-get-frame",
    "api/Layer.js~Layer#frame",
    "member"
  ],
  [
    "api/layer.js~layer#frame",
    "class/api/Layer.js~Layer.html#instance-set-frame",
    "api/Layer.js~Layer#frame",
    "member"
  ],
  [
    "api/layer.js~layer#index",
    "class/api/Layer.js~Layer.html#instance-get-index",
    "api/Layer.js~Layer#index",
    "member"
  ],
  [
    "api/layer.js~layer#isartboard",
    "class/api/Layer.js~Layer.html#instance-get-isArtboard",
    "api/Layer.js~Layer#isArtboard",
    "member"
  ],
  [
    "api/layer.js~layer#isgroup",
    "class/api/Layer.js~Layer.html#instance-get-isGroup",
    "api/Layer.js~Layer#isGroup",
    "member"
  ],
  [
    "api/layer.js~layer#isimage",
    "class/api/Layer.js~Layer.html#instance-get-isImage",
    "api/Layer.js~Layer#isImage",
    "member"
  ],
  [
    "api/layer.js~layer#ispage",
    "class/api/Layer.js~Layer.html#instance-get-isPage",
    "api/Layer.js~Layer#isPage",
    "member"
  ],
  [
    "api/layer.js~layer#isshape",
    "class/api/Layer.js~Layer.html#instance-get-isShape",
    "api/Layer.js~Layer#isShape",
    "member"
  ],
  [
    "api/layer.js~layer#istext",
    "class/api/Layer.js~Layer.html#instance-get-isText",
    "api/Layer.js~Layer#isText",
    "member"
  ],
  [
    "api/layer.js~layer#localrecttopagerect",
    "class/api/Layer.js~Layer.html#instance-method-localRectToPageRect",
    "api/Layer.js~Layer#localRectToPageRect",
    "method"
  ],
  [
    "api/layer.js~layer#localrecttoparentrect",
    "class/api/Layer.js~Layer.html#instance-method-localRectToParentRect",
    "api/Layer.js~Layer#localRectToParentRect",
    "method"
  ],
  [
    "api/layer.js~layer#movebackward",
    "class/api/Layer.js~Layer.html#instance-method-moveBackward",
    "api/Layer.js~Layer#moveBackward",
    "method"
  ],
  [
    "api/layer.js~layer#moveforward",
    "class/api/Layer.js~Layer.html#instance-method-moveForward",
    "api/Layer.js~Layer#moveForward",
    "method"
  ],
  [
    "api/layer.js~layer#movetoback",
    "class/api/Layer.js~Layer.html#instance-method-moveToBack",
    "api/Layer.js~Layer#moveToBack",
    "method"
  ],
  [
    "api/layer.js~layer#movetofront",
    "class/api/Layer.js~Layer.html#instance-method-moveToFront",
    "api/Layer.js~Layer#moveToFront",
    "method"
  ],
  [
    "api/layer.js~layer#name",
    "class/api/Layer.js~Layer.html#instance-set-name",
    "api/Layer.js~Layer#name",
    "member"
  ],
  [
    "api/layer.js~layer#name",
    "class/api/Layer.js~Layer.html#instance-get-name",
    "api/Layer.js~Layer#name",
    "member"
  ],
  [
    "api/layer.js~layer#remove",
    "class/api/Layer.js~Layer.html#instance-method-remove",
    "api/Layer.js~Layer#remove",
    "method"
  ],
  [
    "api/layer.js~layer#select",
    "class/api/Layer.js~Layer.html#instance-method-select",
    "api/Layer.js~Layer#select",
    "method"
  ],
  [
    "api/layer.js~layer.tests",
    "class/api/Layer.js~Layer.html#static-method-tests",
    "api/Layer.js~Layer.tests",
    "method"
  ],
  [
    "api/page.js",
    "file/api/Page.js.html",
    "api/Page.js",
    "file"
  ],
  [
    "api/page.js~page#constructor",
    "class/api/Page.js~Page.html#instance-constructor-constructor",
    "api/Page.js~Page#constructor",
    "method"
  ],
  [
    "api/page.js~page#export",
    "class/api/Page.js~Page.html#instance-method-export",
    "api/Page.js~Page#export",
    "method"
  ],
  [
    "api/page.js~page#exportartboards",
    "class/api/Page.js~Page.html#instance-method-exportArtboards",
    "api/Page.js~Page#exportArtboards",
    "method"
  ],
  [
    "api/page.js~page#ispage",
    "class/api/Page.js~Page.html#instance-get-isPage",
    "api/Page.js~Page#isPage",
    "member"
  ],
  [
    "api/page.js~page#newartboard",
    "class/api/Page.js~Page.html#instance-method-newArtboard",
    "api/Page.js~Page#newArtboard",
    "method"
  ],
  [
    "api/page.js~page#selectedlayers",
    "class/api/Page.js~Page.html#instance-get-selectedLayers",
    "api/Page.js~Page#selectedLayers",
    "member"
  ],
  [
    "api/page.js~page#selectedlayers",
    "class/api/Page.js~Page.html#instance-get-selectedLayers",
    "api/Page.js~Page#selectedLayers",
    "member"
  ],
  [
    "api/page.js~page.tests",
    "class/api/Page.js~Page.html#static-method-tests",
    "api/Page.js~Page.tests",
    "method"
  ],
  [
    "api/rectangle.js",
    "file/api/Rectangle.js.html",
    "api/Rectangle.js",
    "file"
  ],
  [
    "api/rectangle.js~rectangle#ascgrect",
    "class/api/Rectangle.js~Rectangle.html#instance-method-asCGRect",
    "api/Rectangle.js~Rectangle#asCGRect",
    "method"
  ],
  [
    "api/rectangle.js~rectangle#constructor",
    "class/api/Rectangle.js~Rectangle.html#instance-constructor-constructor",
    "api/Rectangle.js~Rectangle#constructor",
    "method"
  ],
  [
    "api/rectangle.js~rectangle#height",
    "class/api/Rectangle.js~Rectangle.html#instance-member-height",
    "api/Rectangle.js~Rectangle#height",
    "member"
  ],
  [
    "api/rectangle.js~rectangle#offset",
    "class/api/Rectangle.js~Rectangle.html#instance-method-offset",
    "api/Rectangle.js~Rectangle#offset",
    "method"
  ],
  [
    "api/rectangle.js~rectangle#tostring",
    "class/api/Rectangle.js~Rectangle.html#instance-method-toString",
    "api/Rectangle.js~Rectangle#toString",
    "method"
  ],
  [
    "api/rectangle.js~rectangle#width",
    "class/api/Rectangle.js~Rectangle.html#instance-member-width",
    "api/Rectangle.js~Rectangle#width",
    "member"
  ],
  [
    "api/rectangle.js~rectangle#x",
    "class/api/Rectangle.js~Rectangle.html#instance-member-x",
    "api/Rectangle.js~Rectangle#x",
    "member"
  ],
  [
    "api/rectangle.js~rectangle#y",
    "class/api/Rectangle.js~Rectangle.html#instance-member-y",
    "api/Rectangle.js~Rectangle#y",
    "member"
  ],
  [
    "api/rectangle.js~rectangle.tests",
    "class/api/Rectangle.js~Rectangle.html#static-method-tests",
    "api/Rectangle.js~Rectangle.tests",
    "method"
  ],
  [
    "api/selection.js",
    "file/api/Selection.js.html",
    "api/Selection.js",
    "file"
  ],
  [
    "api/selection.js~selection#clear",
    "class/api/Selection.js~Selection.html#instance-method-clear",
    "api/Selection.js~Selection#clear",
    "method"
  ],
  [
    "api/selection.js~selection#constructor",
    "class/api/Selection.js~Selection.html#instance-constructor-constructor",
    "api/Selection.js~Selection#constructor",
    "method"
  ],
  [
    "api/selection.js~selection#isempty",
    "class/api/Selection.js~Selection.html#instance-get-isEmpty",
    "api/Selection.js~Selection#isEmpty",
    "member"
  ],
  [
    "api/selection.js~selection#iterate",
    "class/api/Selection.js~Selection.html#instance-method-iterate",
    "api/Selection.js~Selection#iterate",
    "method"
  ],
  [
    "api/selection.js~selection#iteratethenclear",
    "class/api/Selection.js~Selection.html#instance-method-iterateThenClear",
    "api/Selection.js~Selection#iterateThenClear",
    "method"
  ],
  [
    "api/selection.js~selection#iteratewithfilter",
    "class/api/Selection.js~Selection.html#instance-method-iterateWithFilter",
    "api/Selection.js~Selection#iterateWithFilter",
    "method"
  ],
  [
    "api/selection.js~selection#iteratewithfilterthenclear",
    "class/api/Selection.js~Selection.html#instance-method-iterateWithFilterThenClear",
    "api/Selection.js~Selection#iterateWithFilterThenClear",
    "method"
  ],
  [
    "api/selection.js~selection#length",
    "class/api/Selection.js~Selection.html#instance-get-length",
    "api/Selection.js~Selection#length",
    "member"
  ],
  [
    "api/selection.js~selection#nativelayers",
    "class/api/Selection.js~Selection.html#instance-get-nativeLayers",
    "api/Selection.js~Selection#nativeLayers",
    "member"
  ],
  [
    "api/selection.js~selection.tests",
    "class/api/Selection.js~Selection.html#static-method-tests",
    "api/Selection.js~Selection.tests",
    "method"
  ],
  [
    "api/shape.js",
    "file/api/Shape.js.html",
    "api/Shape.js",
    "file"
  ],
  [
    "api/shape.js~shape#constructor",
    "class/api/Shape.js~Shape.html#instance-constructor-constructor",
    "api/Shape.js~Shape#constructor",
    "method"
  ],
  [
    "api/shape.js~shape#isshape",
    "class/api/Shape.js~Shape.html#instance-get-isShape",
    "api/Shape.js~Shape#isShape",
    "member"
  ],
  [
    "api/shape.js~shape#style",
    "class/api/Shape.js~Shape.html#instance-set-style",
    "api/Shape.js~Shape#style",
    "member"
  ],
  [
    "api/shape.js~shape#style",
    "class/api/Shape.js~Shape.html#instance-get-style",
    "api/Shape.js~Shape#style",
    "member"
  ],
  [
    "api/shape.js~shape.tests",
    "class/api/Shape.js~Shape.html#static-method-tests",
    "api/Shape.js~Shape.tests",
    "method"
  ],
  [
    "api/style.js",
    "file/api/Style.js.html",
    "api/Style.js",
    "file"
  ],
  [
    "api/style.js~style#borders",
    "class/api/Style.js~Style.html#instance-set-borders",
    "api/Style.js~Style#borders",
    "member"
  ],
  [
    "api/style.js~style#colorfromstring",
    "class/api/Style.js~Style.html#instance-method-colorFromString",
    "api/Style.js~Style#colorFromString",
    "method"
  ],
  [
    "api/style.js~style#constructor",
    "class/api/Style.js~Style.html#instance-constructor-constructor",
    "api/Style.js~Style#constructor",
    "method"
  ],
  [
    "api/style.js~style#fills",
    "class/api/Style.js~Style.html#instance-set-fills",
    "api/Style.js~Style#fills",
    "member"
  ],
  [
    "api/style.js~style.tests",
    "class/api/Style.js~Style.html#static-method-tests",
    "api/Style.js~Style.tests",
    "method"
  ],
  [
    "api/tester.js",
    "file/api/Tester.js.html",
    "api/Tester.js",
    "file"
  ],
  [
    "api/tester.js~tester#application",
    "class/api/Tester.js~Tester.html#instance-get-application",
    "api/Tester.js~Tester#application",
    "member"
  ],
  [
    "api/tester.js~tester#assert",
    "class/api/Tester.js~Tester.html#instance-method-assert",
    "api/Tester.js~Tester#assert",
    "method"
  ],
  [
    "api/tester.js~tester#assertequal",
    "class/api/Tester.js~Tester.html#instance-method-assertEqual",
    "api/Tester.js~Tester#assertEqual",
    "method"
  ],
  [
    "api/tester.js~tester#assertfalse",
    "class/api/Tester.js~Tester.html#instance-method-assertFalse",
    "api/Tester.js~Tester#assertFalse",
    "method"
  ],
  [
    "api/tester.js~tester#asserttrue",
    "class/api/Tester.js~Tester.html#instance-method-assertTrue",
    "api/Tester.js~Tester#assertTrue",
    "method"
  ],
  [
    "api/tester.js~tester#constructor",
    "class/api/Tester.js~Tester.html#instance-constructor-constructor",
    "api/Tester.js~Tester#constructor",
    "method"
  ],
  [
    "api/tester.js~tester#newtestdocument",
    "class/api/Tester.js~Tester.html#instance-method-newTestDocument",
    "api/Tester.js~Tester#newTestDocument",
    "method"
  ],
  [
    "api/tester.js~tester#rununittests",
    "class/api/Tester.js~Tester.html#instance-method-runUnitTests",
    "api/Tester.js~Tester#runUnitTests",
    "method"
  ],
  [
    "api/text.js",
    "file/api/Text.js.html",
    "api/Text.js",
    "file"
  ],
  [
    "api/text.js~text#adjusttofit",
    "class/api/Text.js~Text.html#instance-method-adjustToFit",
    "api/Text.js~Text#adjustToFit",
    "method"
  ],
  [
    "api/text.js~text#alignment",
    "class/api/Text.js~Text.html#instance-get-alignment",
    "api/Text.js~Text#alignment",
    "member"
  ],
  [
    "api/text.js~text#alignment",
    "class/api/Text.js~Text.html#instance-set-alignment",
    "api/Text.js~Text#alignment",
    "member"
  ],
  [
    "api/text.js~text#constructor",
    "class/api/Text.js~Text.html#instance-constructor-constructor",
    "api/Text.js~Text#constructor",
    "method"
  ],
  [
    "api/text.js~text#fixedwidth",
    "class/api/Text.js~Text.html#instance-set-fixedWidth",
    "api/Text.js~Text#fixedWidth",
    "member"
  ],
  [
    "api/text.js~text#font",
    "class/api/Text.js~Text.html#instance-set-font",
    "api/Text.js~Text#font",
    "member"
  ],
  [
    "api/text.js~text#fragments",
    "class/api/Text.js~Text.html#instance-get-fragments",
    "api/Text.js~Text#fragments",
    "member"
  ],
  [
    "api/text.js~text#frame",
    "class/api/Text.js~Text.html#instance-member-frame",
    "api/Text.js~Text#frame",
    "member"
  ],
  [
    "api/text.js~text#istext",
    "class/api/Text.js~Text.html#instance-get-isText",
    "api/Text.js~Text#isText",
    "member"
  ],
  [
    "api/text.js~text#systemfontsize",
    "class/api/Text.js~Text.html#instance-set-systemFontSize",
    "api/Text.js~Text#systemFontSize",
    "member"
  ],
  [
    "api/text.js~text#text",
    "class/api/Text.js~Text.html#instance-set-text",
    "api/Text.js~Text#text",
    "member"
  ],
  [
    "api/text.js~text#text",
    "class/api/Text.js~Text.html#instance-get-text",
    "api/Text.js~Text#text",
    "member"
  ],
  [
    "api/text.js~text#useconstantbaselines",
    "class/api/Text.js~Text.html#instance-set-useConstantBaselines",
    "api/Text.js~Text#useConstantBaselines",
    "member"
  ],
  [
    "api/text.js~text.tests",
    "class/api/Text.js~Text.html#static-method-tests",
    "api/Text.js~Text.tests",
    "method"
  ],
  [
    "api/wrappedobject.js",
    "file/api/WrappedObject.js.html",
    "api/WrappedObject.js",
    "file"
  ],
  [
    "api/wrappedobject.js~wrappedobject#constructor",
    "class/api/WrappedObject.js~WrappedObject.html#instance-constructor-constructor",
    "api/WrappedObject.js~WrappedObject#constructor",
    "method"
  ],
  [
    "api/wrappedobject.js~wrappedobject#id",
    "class/api/WrappedObject.js~WrappedObject.html#instance-get-id",
    "api/WrappedObject.js~WrappedObject#id",
    "member"
  ],
  [
    "api/wrappedobject.js~wrappedobject#sketchobject",
    "class/api/WrappedObject.js~WrappedObject.html#instance-get-sketchObject",
    "api/WrappedObject.js~WrappedObject#sketchObject",
    "member"
  ],
  [
    "api/wrappedobject.js~wrappedobject.tests",
    "class/api/WrappedObject.js~WrappedObject.html#static-method-tests",
    "api/WrappedObject.js~WrappedObject.tests",
    "method"
  ]
]