window.esdocSearchIndex = [
  [
    "sketch-api/source/application.js~application",
    "class/Source/Application.js~Application.html",
    "<span>Application</span> <span class=\"search-result-import-path\">sketch-api/Source/Application.js</span>",
    "class"
  ],
  [
    "sketch-api/source/artboard.js~artboard",
    "class/Source/Artboard.js~Artboard.html",
    "<span>Artboard</span> <span class=\"search-result-import-path\">sketch-api/Source/Artboard.js</span>",
    "class"
  ],
  [
    "sketch-api/source/document.js~document",
    "class/Source/Document.js~Document.html",
    "<span>Document</span> <span class=\"search-result-import-path\">sketch-api/Source/Document.js</span>",
    "class"
  ],
  [
    "sketch-api/source/group.js~group",
    "class/Source/Group.js~Group.html",
    "<span>Group</span> <span class=\"search-result-import-path\">sketch-api/Source/Group.js</span>",
    "class"
  ],
  [
    "sketch-api/source/image.js~image",
    "class/Source/Image.js~Image.html",
    "<span>Image</span> <span class=\"search-result-import-path\">sketch-api/Source/Image.js</span>",
    "class"
  ],
  [
    "sketch-api/source/layer.js~layer",
    "class/Source/Layer.js~Layer.html",
    "<span>Layer</span> <span class=\"search-result-import-path\">sketch-api/Source/Layer.js</span>",
    "class"
  ],
  [
    "sketch-api/source/page.js~page",
    "class/Source/Page.js~Page.html",
    "<span>Page</span> <span class=\"search-result-import-path\">sketch-api/Source/Page.js</span>",
    "class"
  ],
  [
    "sketch-api/source/rectangle.js~rectangle",
    "class/Source/Rectangle.js~Rectangle.html",
    "<span>Rectangle</span> <span class=\"search-result-import-path\">sketch-api/Source/Rectangle.js</span>",
    "class"
  ],
  [
    "sketch-api/source/shape.js~shape",
    "class/Source/Shape.js~Shape.html",
    "<span>Shape</span> <span class=\"search-result-import-path\">sketch-api/Source/Shape.js</span>",
    "class"
  ],
  [
    "sketch-api/source/text.js~text",
    "class/Source/Text.js~Text.html",
    "<span>Text</span> <span class=\"search-result-import-path\">sketch-api/Source/Text.js</span>",
    "class"
  ],
  [
    "sketch-api/source/wrappedobject.js~wrappedobject",
    "class/Source/WrappedObject.js~WrappedObject.html",
    "<span>WrappedObject</span> <span class=\"search-result-import-path\">sketch-api/Source/WrappedObject.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "source/api.js",
    "file/Source/API.js.html",
    "Source/API.js",
    "file"
  ],
  [
    "source/application.js",
    "file/Source/Application.js.html",
    "Source/Application.js",
    "file"
  ],
  [
    "source/application.js~application#alert",
    "class/Source/Application.js~Application.html#instance-method-alert",
    "Source/Application.js~Application#alert",
    "method"
  ],
  [
    "source/application.js~application#api_version",
    "class/Source/Application.js~Application.html#instance-get-api_version",
    "Source/Application.js~Application#api_version",
    "member"
  ],
  [
    "source/application.js~application#assert",
    "class/Source/Application.js~Application.html#instance-method-assert",
    "Source/Application.js~Application#assert",
    "method"
  ],
  [
    "source/application.js~application#build",
    "class/Source/Application.js~Application.html#instance-get-build",
    "Source/Application.js~Application#build",
    "member"
  ],
  [
    "source/application.js~application#constructor",
    "class/Source/Application.js~Application.html#instance-constructor-constructor",
    "Source/Application.js~Application#constructor",
    "method"
  ],
  [
    "source/application.js~application#context",
    "class/Source/Application.js~Application.html#instance-get-context",
    "Source/Application.js~Application#context",
    "member"
  ],
  [
    "source/application.js~application#factory",
    "class/Source/Application.js~Application.html#instance-member-factory",
    "Source/Application.js~Application#factory",
    "member"
  ],
  [
    "source/application.js~application#getselectionfromuser",
    "class/Source/Application.js~Application.html#instance-method-getSelectionFromUser",
    "Source/Application.js~Application#getSelectionFromUser",
    "method"
  ],
  [
    "source/application.js~application#getstringfromuser",
    "class/Source/Application.js~Application.html#instance-method-getStringFromUser",
    "Source/Application.js~Application#getStringFromUser",
    "method"
  ],
  [
    "source/application.js~application#log",
    "class/Source/Application.js~Application.html#instance-method-log",
    "Source/Application.js~Application#log",
    "method"
  ],
  [
    "source/application.js~application#message",
    "class/Source/Application.js~Application.html#instance-method-message",
    "Source/Application.js~Application#message",
    "method"
  ],
  [
    "source/application.js~application#metadata",
    "class/Source/Application.js~Application.html#instance-member-metadata",
    "Source/Application.js~Application#metadata",
    "member"
  ],
  [
    "source/application.js~application#newdocument",
    "class/Source/Application.js~Application.html#instance-method-newDocument",
    "Source/Application.js~Application#newDocument",
    "method"
  ],
  [
    "source/application.js~application#rectangle",
    "class/Source/Application.js~Application.html#instance-method-rectangle",
    "Source/Application.js~Application#rectangle",
    "method"
  ],
  [
    "source/application.js~application#resourcenamed",
    "class/Source/Application.js~Application.html#instance-method-resourceNamed",
    "Source/Application.js~Application#resourceNamed",
    "method"
  ],
  [
    "source/application.js~application#selecteddocument",
    "class/Source/Application.js~Application.html#instance-get-selectedDocument",
    "Source/Application.js~Application#selectedDocument",
    "member"
  ],
  [
    "source/application.js~application#setsettingforkey",
    "class/Source/Application.js~Application.html#instance-method-setSettingForKey",
    "Source/Application.js~Application#setSettingForKey",
    "method"
  ],
  [
    "source/application.js~application#settingforkey",
    "class/Source/Application.js~Application.html#instance-method-settingForKey",
    "Source/Application.js~Application#settingForKey",
    "method"
  ],
  [
    "source/application.js~application#version",
    "class/Source/Application.js~Application.html#instance-get-version",
    "Source/Application.js~Application#version",
    "member"
  ],
  [
    "source/artboard.js",
    "file/Source/Artboard.js.html",
    "Source/Artboard.js",
    "file"
  ],
  [
    "source/artboard.js~artboard#constructor",
    "class/Source/Artboard.js~Artboard.html#instance-constructor-constructor",
    "Source/Artboard.js~Artboard#constructor",
    "method"
  ],
  [
    "source/artboard.js~artboard#isartboard",
    "class/Source/Artboard.js~Artboard.html#instance-get-isArtboard",
    "Source/Artboard.js~Artboard#isArtboard",
    "member"
  ],
  [
    "source/document.js",
    "file/Source/Document.js.html",
    "Source/Document.js",
    "file"
  ],
  [
    "source/document.js~document#application",
    "class/Source/Document.js~Document.html#instance-member-application",
    "Source/Document.js~Document#application",
    "member"
  ],
  [
    "source/document.js~document#constructor",
    "class/Source/Document.js~Document.html#instance-constructor-constructor",
    "Source/Document.js~Document#constructor",
    "method"
  ],
  [
    "source/document.js~document#layernamed",
    "class/Source/Document.js~Document.html#instance-method-layerNamed",
    "Source/Document.js~Document#layerNamed",
    "method"
  ],
  [
    "source/document.js~document#layerwithid",
    "class/Source/Document.js~Document.html#instance-method-layerWithID",
    "Source/Document.js~Document#layerWithID",
    "method"
  ],
  [
    "source/document.js~document#pages",
    "class/Source/Document.js~Document.html#instance-get-pages",
    "Source/Document.js~Document#pages",
    "member"
  ],
  [
    "source/document.js~document#selectedlayers",
    "class/Source/Document.js~Document.html#instance-get-selectedLayers",
    "Source/Document.js~Document#selectedLayers",
    "member"
  ],
  [
    "source/document.js~document#selectedpage",
    "class/Source/Document.js~Document.html#instance-get-selectedPage",
    "Source/Document.js~Document#selectedPage",
    "member"
  ],
  [
    "source/group.js",
    "file/Source/Group.js.html",
    "Source/Group.js",
    "file"
  ],
  [
    "source/group.js~group#constructor",
    "class/Source/Group.js~Group.html#instance-constructor-constructor",
    "Source/Group.js~Group#constructor",
    "method"
  ],
  [
    "source/group.js~group#is_group",
    "class/Source/Group.js~Group.html#instance-method-is_group",
    "Source/Group.js~Group#is_group",
    "method"
  ],
  [
    "source/image.js",
    "file/Source/Image.js.html",
    "Source/Image.js",
    "file"
  ],
  [
    "source/image.js~image#constructor",
    "class/Source/Image.js~Image.html#instance-constructor-constructor",
    "Source/Image.js~Image#constructor",
    "method"
  ],
  [
    "source/image.js~image#imageurl",
    "class/Source/Image.js~Image.html#instance-set-imageURL",
    "Source/Image.js~Image#imageURL",
    "member"
  ],
  [
    "source/image.js~image#isimage",
    "class/Source/Image.js~Image.html#instance-get-isImage",
    "Source/Image.js~Image#isImage",
    "member"
  ],
  [
    "source/layer.js",
    "file/Source/Layer.js.html",
    "Source/Layer.js",
    "file"
  ],
  [
    "source/layer.js~layer#addtoselection",
    "class/Source/Layer.js~Layer.html#instance-method-addToSelection",
    "Source/Layer.js~Layer#addToSelection",
    "method"
  ],
  [
    "source/layer.js~layer#addwrappedlayerwithproperties",
    "class/Source/Layer.js~Layer.html#instance-method-addWrappedLayerWithProperties",
    "Source/Layer.js~Layer#addWrappedLayerWithProperties",
    "method"
  ],
  [
    "source/layer.js~layer#constructor",
    "class/Source/Layer.js~Layer.html#instance-constructor-constructor",
    "Source/Layer.js~Layer#constructor",
    "method"
  ],
  [
    "source/layer.js~layer#deselect",
    "class/Source/Layer.js~Layer.html#instance-method-deselect",
    "Source/Layer.js~Layer#deselect",
    "method"
  ],
  [
    "source/layer.js~layer#document",
    "class/Source/Layer.js~Layer.html#instance-member-document",
    "Source/Layer.js~Layer#document",
    "member"
  ],
  [
    "source/layer.js~layer#duplicate",
    "class/Source/Layer.js~Layer.html#instance-method-duplicate",
    "Source/Layer.js~Layer#duplicate",
    "method"
  ],
  [
    "source/layer.js~layer#frame",
    "class/Source/Layer.js~Layer.html#instance-set-frame",
    "Source/Layer.js~Layer#frame",
    "member"
  ],
  [
    "source/layer.js~layer#frame",
    "class/Source/Layer.js~Layer.html#instance-get-frame",
    "Source/Layer.js~Layer#frame",
    "member"
  ],
  [
    "source/layer.js~layer#frameforlayerwithproperties",
    "class/Source/Layer.js~Layer.html#instance-method-frameForLayerWithProperties",
    "Source/Layer.js~Layer#frameForLayerWithProperties",
    "method"
  ],
  [
    "source/layer.js~layer#isartboard",
    "class/Source/Layer.js~Layer.html#instance-get-isArtboard",
    "Source/Layer.js~Layer#isArtboard",
    "member"
  ],
  [
    "source/layer.js~layer#isgroup",
    "class/Source/Layer.js~Layer.html#instance-get-isGroup",
    "Source/Layer.js~Layer#isGroup",
    "member"
  ],
  [
    "source/layer.js~layer#isimage",
    "class/Source/Layer.js~Layer.html#instance-get-isImage",
    "Source/Layer.js~Layer#isImage",
    "member"
  ],
  [
    "source/layer.js~layer#ispage",
    "class/Source/Layer.js~Layer.html#instance-get-isPage",
    "Source/Layer.js~Layer#isPage",
    "member"
  ],
  [
    "source/layer.js~layer#isshape",
    "class/Source/Layer.js~Layer.html#instance-get-isShape",
    "Source/Layer.js~Layer#isShape",
    "member"
  ],
  [
    "source/layer.js~layer#istext",
    "class/Source/Layer.js~Layer.html#instance-get-isText",
    "Source/Layer.js~Layer#isText",
    "member"
  ],
  [
    "source/layer.js~layer#iterate",
    "class/Source/Layer.js~Layer.html#instance-method-iterate",
    "Source/Layer.js~Layer#iterate",
    "method"
  ],
  [
    "source/layer.js~layer#name",
    "class/Source/Layer.js~Layer.html#instance-get-name",
    "Source/Layer.js~Layer#name",
    "member"
  ],
  [
    "source/layer.js~layer#name",
    "class/Source/Layer.js~Layer.html#instance-set-name",
    "Source/Layer.js~Layer#name",
    "member"
  ],
  [
    "source/layer.js~layer#newartboard",
    "class/Source/Layer.js~Layer.html#instance-method-newArtboard",
    "Source/Layer.js~Layer#newArtboard",
    "method"
  ],
  [
    "source/layer.js~layer#newgroup",
    "class/Source/Layer.js~Layer.html#instance-method-newGroup",
    "Source/Layer.js~Layer#newGroup",
    "method"
  ],
  [
    "source/layer.js~layer#newimage",
    "class/Source/Layer.js~Layer.html#instance-method-newImage",
    "Source/Layer.js~Layer#newImage",
    "method"
  ],
  [
    "source/layer.js~layer#newshape",
    "class/Source/Layer.js~Layer.html#instance-method-newShape",
    "Source/Layer.js~Layer#newShape",
    "method"
  ],
  [
    "source/layer.js~layer#newtext",
    "class/Source/Layer.js~Layer.html#instance-method-newText",
    "Source/Layer.js~Layer#newText",
    "method"
  ],
  [
    "source/layer.js~layer#remove",
    "class/Source/Layer.js~Layer.html#instance-method-remove",
    "Source/Layer.js~Layer#remove",
    "method"
  ],
  [
    "source/layer.js~layer#select",
    "class/Source/Layer.js~Layer.html#instance-method-select",
    "Source/Layer.js~Layer#select",
    "method"
  ],
  [
    "source/page.js",
    "file/Source/Page.js.html",
    "Source/Page.js",
    "file"
  ],
  [
    "source/page.js~page#constructor",
    "class/Source/Page.js~Page.html#instance-constructor-constructor",
    "Source/Page.js~Page#constructor",
    "method"
  ],
  [
    "source/page.js~page#document",
    "class/Source/Page.js~Page.html#instance-member-document",
    "Source/Page.js~Page#document",
    "member"
  ],
  [
    "source/page.js~page#ispage",
    "class/Source/Page.js~Page.html#instance-get-isPage",
    "Source/Page.js~Page#isPage",
    "member"
  ],
  [
    "source/rectangle.js",
    "file/Source/Rectangle.js.html",
    "Source/Rectangle.js",
    "file"
  ],
  [
    "source/rectangle.js~rectangle#ascgrect",
    "class/Source/Rectangle.js~Rectangle.html#instance-method-asCGRect",
    "Source/Rectangle.js~Rectangle#asCGRect",
    "method"
  ],
  [
    "source/rectangle.js~rectangle#constructor",
    "class/Source/Rectangle.js~Rectangle.html#instance-constructor-constructor",
    "Source/Rectangle.js~Rectangle#constructor",
    "method"
  ],
  [
    "source/rectangle.js~rectangle#height",
    "class/Source/Rectangle.js~Rectangle.html#instance-member-height",
    "Source/Rectangle.js~Rectangle#height",
    "member"
  ],
  [
    "source/rectangle.js~rectangle#width",
    "class/Source/Rectangle.js~Rectangle.html#instance-member-width",
    "Source/Rectangle.js~Rectangle#width",
    "member"
  ],
  [
    "source/rectangle.js~rectangle#x",
    "class/Source/Rectangle.js~Rectangle.html#instance-member-x",
    "Source/Rectangle.js~Rectangle#x",
    "member"
  ],
  [
    "source/rectangle.js~rectangle#y",
    "class/Source/Rectangle.js~Rectangle.html#instance-member-y",
    "Source/Rectangle.js~Rectangle#y",
    "member"
  ],
  [
    "source/shape.js",
    "file/Source/Shape.js.html",
    "Source/Shape.js",
    "file"
  ],
  [
    "source/shape.js~shape#constructor",
    "class/Source/Shape.js~Shape.html#instance-constructor-constructor",
    "Source/Shape.js~Shape#constructor",
    "method"
  ],
  [
    "source/shape.js~shape#isshape",
    "class/Source/Shape.js~Shape.html#instance-get-isShape",
    "Source/Shape.js~Shape#isShape",
    "member"
  ],
  [
    "source/text.js",
    "file/Source/Text.js.html",
    "Source/Text.js",
    "file"
  ],
  [
    "source/text.js~text#alignment",
    "class/Source/Text.js~Text.html#instance-set-alignment",
    "Source/Text.js~Text#alignment",
    "member"
  ],
  [
    "source/text.js~text#constructor",
    "class/Source/Text.js~Text.html#instance-constructor-constructor",
    "Source/Text.js~Text#constructor",
    "method"
  ],
  [
    "source/text.js~text#fixedwidth",
    "class/Source/Text.js~Text.html#instance-set-fixedWidth",
    "Source/Text.js~Text#fixedWidth",
    "member"
  ],
  [
    "source/text.js~text#font",
    "class/Source/Text.js~Text.html#instance-set-font",
    "Source/Text.js~Text#font",
    "member"
  ],
  [
    "source/text.js~text#istext",
    "class/Source/Text.js~Text.html#instance-get-isText",
    "Source/Text.js~Text#isText",
    "member"
  ],
  [
    "source/text.js~text#systemfontsize",
    "class/Source/Text.js~Text.html#instance-set-systemFontSize",
    "Source/Text.js~Text#systemFontSize",
    "member"
  ],
  [
    "source/text.js~text#text",
    "class/Source/Text.js~Text.html#instance-set-text",
    "Source/Text.js~Text#text",
    "member"
  ],
  [
    "source/text.js~text#text",
    "class/Source/Text.js~Text.html#instance-get-text",
    "Source/Text.js~Text#text",
    "member"
  ],
  [
    "source/wrappedobject.js",
    "file/Source/WrappedObject.js.html",
    "Source/WrappedObject.js",
    "file"
  ],
  [
    "source/wrappedobject.js~wrappedobject#constructor",
    "class/Source/WrappedObject.js~WrappedObject.html#instance-constructor-constructor",
    "Source/WrappedObject.js~WrappedObject#constructor",
    "method"
  ],
  [
    "source/wrappedobject.js~wrappedobject#id",
    "class/Source/WrappedObject.js~WrappedObject.html#instance-get-id",
    "Source/WrappedObject.js~WrappedObject#id",
    "member"
  ],
  [
    "source/wrappedobject.js~wrappedobject#object",
    "class/Source/WrappedObject.js~WrappedObject.html#instance-member-object",
    "Source/WrappedObject.js~WrappedObject#object",
    "member"
  ]
]